### model
model_name_or_path: model/base/qwen3-coder-next
adapter_name_or_path: training_artifacts/qwen3-coder-next/lora/full
template: qwen3_nothink
trust_remote_code: true
low_cpu_mem_usage: true

### method
finetuning_type: lora

### export
export_dir: model/merged/aegislm-qwen3-coder-next-20260728T100259
export_size: 5
export_device: cpu
export_legacy_format: false
